### ISSUE TITLE
Floating point values compared using ==

### ISSUE THREAD

**Issue by sapradhan** [jdereg/java-util#2]
The following test fails

```
test() {
    Class1 x = new Class1(true, Math.tan(Math.PI / 4), 1);
    Class1 y = new Class1(true, 1.0, 1);
    assertTrue(DeepEquals.deepEquals(x, y));
}

class Class1 {
    private boolean b;
    private double d;
    int i;

    public Class1(boolean b, double d, int i) {
        super();
        this.b = b;
        this.d = d;
        this.i = i;
    }

}
```

**Comment by Erhannis** [comment]
I assert that "nearly equal" should not be the default behavior.  I agree that it's important to be ABLE to specify an epsilon, but I would have expected the default to be "exactly equal", and surprising a developer is a source of bugs.  Suppose I'm dealing with Bitcoin, and a few hundred people each lose a dime because the value change was considered to be too small?  Or a particle physicist loses some of his neutrinos because an optimization thought that nothing had moved?  Mitigations about "relative error" notwithstanding, when I ask if two objects are deeply equal, I want to know whether they will behave exactly the same in all (reasonable) situations.  The new implementation does not do this.  I assert that nearlyEqual should only be applied when the user requests it.
